name: CI/CD on github
on:  [push, pull_request]
jobs:
  build-gcc:
    name: build with GCC (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: check code
        uses: actions/checkout@v4

      - name: Install compil:
        run: |
          sudo apt-get update
          sudo apte-get install -y cmake g++

      - name: configure with CMake:
        run: cmake -H. -B_build -DCMAKE_CXX_COMPILER=g++

      - name: build project:
        run: cmake --build _build
  build-clang:
    name: build with Clang (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: check code
        uses: actions/checkout@v4

      - name: Install compil:
        run: |
          sudo apt-get update
          sudo apte-get install -y cmake clang

      - name: configure with CMake:
        run: cmake -H. -B_build -DCMAKE_CXX_COMPILER=clang++

      - name: build project:
        run: cmake --build _build
  build-windows:
    name: build with VS 
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: configure with CMake:
        run: cmake -H. -B_build -G "Visual Studio 17 2022" -A x64

      - name: build project:
        run: cmake --build _build --config Release